DEFINE
	VAR selected_start = MIN('Dim Date'[day])
	VAR selected_end = MAX('Dim Date'[day])
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('Dim Date'[day])),
			AND('Dim Date'[day] >= selected_start, 'Dim Date'[day] < selected_end)
		)

	VAR __DS0FilterTable2 = 
		TREATAS({"'KPIs'[Invoices Count]"}, 'Invoice KPIs'[Invoice KPIs Champs])

	VAR __DS0FilterTable3 = 
		TREATAS({"'Dim Date'[year_month]"}, 'Date Hierarchy Filter'[Paramètre Champs])

	VAR __DS0Core = 
		CALCULATETABLE(
			SUMMARIZE(
				'Fact Invoices',
				'Fact Invoices'[invoice_id],
				'Fact Invoices'[expected_payment_date],
				'Fact Invoices'[performed_payment_date],
				'Fact Invoices'[invoice_date],
				'Fact Invoices'[invoice_payment_method],
				'Fact Invoices'[is_closed],
				'Fact Invoices'[turnover_invoiced_TE],
				'Fact Invoices'[agency_id],
				'Fact Invoices'[client_name],
				'Fact Invoices'[client_id],
				'Fact Invoices'[invoice_state_name]
			),
			KEEPFILTERS(__DS0FilterTable),
			KEEPFILTERS(__DS0FilterTable2),
			KEEPFILTERS(__DS0FilterTable3)
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			501,
			__DS0Core,
			'Fact Invoices'[invoice_id],
			1,
			'Fact Invoices'[expected_payment_date],
			1,
			'Fact Invoices'[performed_payment_date],
			1,
			'Fact Invoices'[invoice_date],
			1,
			'Fact Invoices'[invoice_payment_method],
			1,
			'Fact Invoices'[is_closed],
			1,
			'Fact Invoices'[turnover_invoiced_TE],
			1,
			'Fact Invoices'[agency_id],
			1,
			'Fact Invoices'[client_name],
			1,
			'Fact Invoices'[client_id],
			1,
			'Fact Invoices'[invoice_state_name],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Fact Invoices'[invoice_id],
	'Fact Invoices'[expected_payment_date],
	'Fact Invoices'[performed_payment_date],
	'Fact Invoices'[invoice_date],
	'Fact Invoices'[invoice_payment_method],
	'Fact Invoices'[is_closed],
	'Fact Invoices'[turnover_invoiced_TE],
	'Fact Invoices'[agency_id],
	'Fact Invoices'[client_name],
	'Fact Invoices'[client_id],
	'Fact Invoices'[invoice_state_name]